/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as StandupsIndexImport } from './routes/standups.index'
import { Route as StandupsStandupIdImport } from './routes/standups.$standupId'
import { Route as StandupsStandupIdIndexImport } from './routes/standups.$standupId.index'
import { Route as StandupsStandupIdUpdateImport } from './routes/standups.$standupId.update'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const StandupsIndexRoute = StandupsIndexImport.update({
  id: '/standups/',
  path: '/standups/',
  getParentRoute: () => rootRoute,
} as any)

const StandupsStandupIdRoute = StandupsStandupIdImport.update({
  id: '/standups/$standupId',
  path: '/standups/$standupId',
  getParentRoute: () => rootRoute,
} as any)

const StandupsStandupIdIndexRoute = StandupsStandupIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StandupsStandupIdRoute,
} as any)

const StandupsStandupIdUpdateRoute = StandupsStandupIdUpdateImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => StandupsStandupIdRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/standups/$standupId': {
      id: '/standups/$standupId'
      path: '/standups/$standupId'
      fullPath: '/standups/$standupId'
      preLoaderRoute: typeof StandupsStandupIdImport
      parentRoute: typeof rootRoute
    }
    '/standups/': {
      id: '/standups/'
      path: '/standups'
      fullPath: '/standups'
      preLoaderRoute: typeof StandupsIndexImport
      parentRoute: typeof rootRoute
    }
    '/standups/$standupId/update': {
      id: '/standups/$standupId/update'
      path: '/update'
      fullPath: '/standups/$standupId/update'
      preLoaderRoute: typeof StandupsStandupIdUpdateImport
      parentRoute: typeof StandupsStandupIdImport
    }
    '/standups/$standupId/': {
      id: '/standups/$standupId/'
      path: '/'
      fullPath: '/standups/$standupId/'
      preLoaderRoute: typeof StandupsStandupIdIndexImport
      parentRoute: typeof StandupsStandupIdImport
    }
  }
}

// Create and export the route tree

interface StandupsStandupIdRouteChildren {
  StandupsStandupIdUpdateRoute: typeof StandupsStandupIdUpdateRoute
  StandupsStandupIdIndexRoute: typeof StandupsStandupIdIndexRoute
}

const StandupsStandupIdRouteChildren: StandupsStandupIdRouteChildren = {
  StandupsStandupIdUpdateRoute: StandupsStandupIdUpdateRoute,
  StandupsStandupIdIndexRoute: StandupsStandupIdIndexRoute,
}

const StandupsStandupIdRouteWithChildren =
  StandupsStandupIdRoute._addFileChildren(StandupsStandupIdRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/standups/$standupId': typeof StandupsStandupIdRouteWithChildren
  '/standups': typeof StandupsIndexRoute
  '/standups/$standupId/update': typeof StandupsStandupIdUpdateRoute
  '/standups/$standupId/': typeof StandupsStandupIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/standups': typeof StandupsIndexRoute
  '/standups/$standupId/update': typeof StandupsStandupIdUpdateRoute
  '/standups/$standupId': typeof StandupsStandupIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/standups/$standupId': typeof StandupsStandupIdRouteWithChildren
  '/standups/': typeof StandupsIndexRoute
  '/standups/$standupId/update': typeof StandupsStandupIdUpdateRoute
  '/standups/$standupId/': typeof StandupsStandupIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/standups/$standupId'
    | '/standups'
    | '/standups/$standupId/update'
    | '/standups/$standupId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/standups'
    | '/standups/$standupId/update'
    | '/standups/$standupId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/standups/$standupId'
    | '/standups/'
    | '/standups/$standupId/update'
    | '/standups/$standupId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  StandupsStandupIdRoute: typeof StandupsStandupIdRouteWithChildren
  StandupsIndexRoute: typeof StandupsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  StandupsStandupIdRoute: StandupsStandupIdRouteWithChildren,
  StandupsIndexRoute: StandupsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/standups/$standupId",
        "/standups/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/standups/$standupId": {
      "filePath": "standups.$standupId.tsx",
      "children": [
        "/standups/$standupId/update",
        "/standups/$standupId/"
      ]
    },
    "/standups/": {
      "filePath": "standups.index.tsx"
    },
    "/standups/$standupId/update": {
      "filePath": "standups.$standupId.update.tsx",
      "parent": "/standups/$standupId"
    },
    "/standups/$standupId/": {
      "filePath": "standups.$standupId.index.tsx",
      "parent": "/standups/$standupId"
    }
  }
}
ROUTE_MANIFEST_END */
